services:
  - type: web
    name: estim-dvf
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
