services:
  - type: web
    name: estim-dvf
    runtime: node
    buildCommand: npm install && npm --prefix server install && npm --prefix client install && npm --prefix client run build
    startCommand: NODE_ENV=production node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
